---
namespace: "victorock"
name: "autogen"
version: "2.8.0"
authors:
  - "Victor da Costa @victorobotz:twitter"
description: "Autogenerates wrapped Playbooks and Tasks from Ansible Modules."
license: "GPL-3.0-or-later"
tags:
  - "content"
  - "cloud"
  - "clustering"
  - "commands"
  - "crypto"
  - "database"
  - "files"
  - "identity"
  - "import_tower"
  - "inventory"
  - "messaging"
  - "monitoring"
  - "net_tools"
  - "network"
  - "notification"
  - "packaging"
  - "remote_management"
  - "source_control"
  - "storage"
  - "system"
  - "utilities"
  - "web_infrastructure"
  - "windows"
dependencies: []
repository: "https://github.com/victorock/ansible-playground"
