---
- name: "Get plugin facts"
  r_plugin_facts:
    name: "{{ autogen_plugin_name | default(omit, True) }}"
    type: "{{ pautogen_plugin_type | default(omit, True) }}"
  register: r_plugin_facts

# due the amount of namespaces, 'loop' is veeeeery slow
# TODO: find a more efficient way to loop over
- name: "Create playbooks folder structure"
  vars:
    matches: "{{ r_plugin_facts.plugin | selectattr('namespace', 'match', autogen_plugin_namespace) }}"
  file:
    path: "{{ autogen_path }}/playbooks/{{ namespace }}"
    state: "directory"
  loop: "{{ matches | map(attribute='namespace') | unique | list }}"
  loop_control:
    loop_var: namespace
    label: "{{ namespace }}"

# due the amount of namespaces, 'loop' is veeeeery slow
# TODO: find a more efficient way to loop over
- name: "Create tasks folder structure"
  vars:
    matches: "{{ r_plugin_facts.plugin | selectattr('namespace', 'match', autogen_plugin_namespace) }}"
  file:
    path: "{{ autogen_path }}/tasks/{{ namespace }}"
    state: "directory"
  loop: "{{ matches | map(attribute='namespace') | unique | list }}"
  loop_control:
    loop_var: namespace
    label: "{{ namespace }}"

# due the amount of namespaces, 'loop' is veeeeery slow
# TODO: find a more efficient way to loop over
- name: "Generate playbook content"
  vars:
    matches: "{{ r_plugin_facts.plugin | selectattr('namespace', 'match', autogen_plugin_namespace) }}"
  template:
    src: "playbook.j2"
    dest: "{{ autogen_path }}/playbooks/{{ plugin.value.namespace }}/{{ plugin.key }}.yaml"
  loop: "{{ matches | dict2items }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin.key }}"

# due the amount of namespaces, 'loop' is veeeeery slow
# TODO: find a more efficient way to loop over
- name: "Generate tasks content"
  vars:
    matches: "{{ r_plugin_facts.plugin | selectattr('namespace', 'match', autogen_plugin_namespace) }}"
  template:
    src: "task.j2"
    dest: "{{ autogen_path }}/tasks/{{ plugin.value.namespace }}/{{ plugin.key }}.yaml"
  loop: "{{ matches | dict2items }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin.key }}"

- name: "Generate import_tower"
  template:
    src: "import_tower.yaml.j2"
    dest: "{{ autogen_path }}/playbooks/import_tower.yaml"
